apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hb40779/platform-repo.git
    targetRevision: main
    path: helm/app-template
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/hb40779/hello-world-app/main/values-hello-api.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

