apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hb40779/platform-repo.git
    targetRevision: main
    path: helm/app-template
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/hb40779/hello-world-app/main/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: playground
  syncPolicy:
    automated:
      prune: true
      selfHeal: true




